### ISSUE TITLE
Log4j vulnerability for Remnux

### ISSUE THREAD

**Issue by faleon** [digitalsleuth/sift-remnux#1]
Hello, can this container be updated for the Log4j vulnerability? I can update the remnux in the container itself but if it gets redeployed it loses the patches.

https://htmlpreview.github.io/?https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_10.1_build/Ghidra/Configurations/Public_Release/src/global/docs/WhatsNew.html

**Comment by digitalsleuth** [comment]
Good morning @faleon , I'll get this updated shortly!

**Comment by digitalsleuth** [comment]
Updated now @faleon!
